server:
  port: 8023
spring:
  datasource:
   ## driver-class-name: com.mysql.cj.jdbc.Driver
   ## url: jdbc:mysql://127.0.0.1:3306/NonContact?useUnicode=true&characterEncoding=utf8&autoReconnect=true&serverTimezone=Asia/Seoul&useOldAliasMetadataBehavior=true&zeroDateTimeNehavior=convertToNull
    driver-class-name: net.sf.log4jdbc.sql.jdbcapi.DriverSpy
    url: jdbc:log4jdbc:mysql://127.0.0.1:3306/NonContact?useUnicode=true&characterEncoding=utf8&autoReconnect=true&serverTimezone=Asia/Seoul&useOldAliasMetadataBehavior=true&zeroDateTimeNehavior=convertToNull
    username: sbsst
    password: sbs123414
mybatis:
  type-aliases-package: com.NonContact.dto
custom:
  logging:
    dir: log
    level: debug 